// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://znwklgcozodofjascbna.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpud2tsZ2Nvem9kb2ZqYXNjYm5hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0MzExODgsImV4cCI6MjA3MDAwNzE4OH0.oYb252dBiMdik0gkAMfI2veDyngLpXR7W2Ya6Wxr2WY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});